spring:
  application:
    name: Food-Fusion-Platform
  datasource:
    url: 
      - jdbc:h2:mem:testdb
      - jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
